---
- hosts: [kaisen-ec2]
  become: true
  become_user: root
  tasks:
    - name: Installation of nginx
      ansible.builtin.apt:
        name: nginx
        update_cache: yes

    - name: Installation of the configuration
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html
        owner: www-data
        group: www-data
        mode: '0755'
